#!/usr/bin/env python3
"""
PSE_ACUTE_THALAMUS_VOLUME_ASSOCIATION_01.py

Final descriptive analysis for the acute thalamic pilot:
association between acute ischemic lesion volume and thalamic asymmetry.

Input
-----
Uses the patient-level table already generated by:
    PSE_ACUTE_THALAMUS_LESION_AWARE_ANALYSIS_01.py

Expected file:
    <PSE_ROOT>/derivatives/
    acute_pilot_thalamus_lesion_aware/
    PSE_ACUTE_THALAMUS_PATIENT_LEVEL_v01.csv

Primary modalities
------------------
    FDG-PET
    ASL-CBF
    CTP-CBF

Primary asymmetry measure
-------------------------
    Median AI = (ipsi - contra) / (ipsi + contra)

Interpretation
--------------
AI < 0 means lower ipsilateral thalamic value.

Spearman rho is reported DESCRIPTIVELY ONLY.
No p-values or inferential tests are produced because this is a very small
exploratory pilot.

Groups
------
1. ALL
2. THALAMUS_SPARED_LT1PCT
3. STRICT_DEEP_ROI_SPARED

Outputs
-------
<PSE_ROOT>/derivatives/
acute_pilot_thalamus_volume_association/

    PSE_ACUTE_THALAMUS_VOLUME_PATIENT_LEVEL_v01.csv
    PSE_ACUTE_THALAMUS_VOLUME_SPEARMAN_v01.csv

    PSE_ACUTE_THALAMUS_VOLUME_vs_FDG-PET_AI_v01.png
    PSE_ACUTE_THALAMUS_VOLUME_vs_ASL-CBF_AI_v01.png
    PSE_ACUTE_THALAMUS_VOLUME_vs_CTP-CBF_AI_v01.png

Each figure contains individual subjects only.
Subjects with direct ipsilateral thalamic overlap >=1% are marked by a dagger
(†) in their annotation.

Usage
-----
    conda activate pse-stroke
    cd <PSE_ROOT>/code
    python PSE_ACUTE_THALAMUS_VOLUME_ASSOCIATION_01.py
"""

from __future__ import annotations

import os

import csv
from pathlib import Path

import numpy as np
from scipy.stats import spearmanr

try:
    import matplotlib.pyplot as plt
except ImportError as exc:
    raise SystemExit(
        "matplotlib is required. Install it with:\n"
        "  conda install matplotlib -y"
    ) from exc


# ============================================================================
# Paths

ROOT = Path(os.environ.get("PSE_ROOT", str(Path.home() / "PSE"))).expanduser().resolve()

INPUT_FILE = (
    ROOT
    / "derivatives"
    / "acute_pilot_thalamus_lesion_aware"
    / "PSE_ACUTE_THALAMUS_PATIENT_LEVEL_v01.csv"
)

OUT_DIR = (
    ROOT
    / "derivatives"
    / "acute_pilot_thalamus_volume_association"
)

PATIENT_OUT = OUT_DIR / "PSE_ACUTE_THALAMUS_VOLUME_PATIENT_LEVEL_v01.csv"
SPEARMAN_OUT = OUT_DIR / "PSE_ACUTE_THALAMUS_VOLUME_SPEARMAN_v01.csv"


MODALITIES = {
    "FDG-PET": "PET_FDG_AI",
    "ASL-CBF": "ASL_CBF_AI",
    "CTP-CBF": "CTP_CBF_AI",
}


# ============================================================================
# Utilities

def to_float(value):
    if value is None:
        return np.nan

    s = str(value).strip()

    if s == "" or s.lower() == "nan":
        return np.nan

    try:
        return float(s)
    except ValueError:
        return np.nan


def to_bool(value):
    return str(value).strip().lower() in {"true", "1", "yes", "y"}


def fmt(value, nd=6):
    if value is None:
        return ""

    try:
        x = float(value)
    except Exception:
        return ""

    if not np.isfinite(x):
        return ""

    return f"{x:.{nd}f}"


def read_patient_table():
    rows = []

    with INPUT_FILE.open(
        "r",
        newline="",
        encoding="utf-8-sig",
    ) as f:
        reader = csv.DictReader(f)

        required = {
            "Subject",
            "StrokeSide",
            "LesionVolume_mL",
            "Thalamus_IpsiOverlapPercent",
            "Hippocampus_IpsiOverlapPercent",
            "ThalamusDirect_GE1pct",
            "DeepROI_AnyOverlap",
            "PET_FDG_AI",
            "ASL_CBF_AI",
            "CTP_CBF_AI",
        }

        missing = required.difference(reader.fieldnames or [])

        if missing:
            raise RuntimeError(
                "Missing required columns in patient-level file: "
                + ", ".join(sorted(missing))
            )

        for row in reader:
            rows.append(
                {
                    "Subject": row["Subject"].strip(),
                    "StrokeSide": row["StrokeSide"].strip(),
                    "LesionVolume_mL": to_float(
                        row["LesionVolume_mL"]
                    ),
                    "Thalamus_IpsiOverlapPercent": to_float(
                        row["Thalamus_IpsiOverlapPercent"]
                    ),
                    "Hippocampus_IpsiOverlapPercent": to_float(
                        row["Hippocampus_IpsiOverlapPercent"]
                    ),
                    "ThalamusDirect_GE1pct": to_bool(
                        row["ThalamusDirect_GE1pct"]
                    ),
                    "DeepROI_AnyOverlap": to_bool(
                        row["DeepROI_AnyOverlap"]
                    ),
                    "PET_FDG_AI": to_float(
                        row["PET_FDG_AI"]
                    ),
                    "ASL_CBF_AI": to_float(
                        row["ASL_CBF_AI"]
                    ),
                    "CTP_CBF_AI": to_float(
                        row["CTP_CBF_AI"]
                    ),
                }
            )

    return rows


def group_rows(rows, group):
    if group == "ALL":
        return list(rows)

    if group == "THALAMUS_SPARED_LT1PCT":
        return [
            r
            for r in rows
            if not r["ThalamusDirect_GE1pct"]
        ]

    if group == "STRICT_DEEP_ROI_SPARED":
        return [
            r
            for r in rows
            if not r["DeepROI_AnyOverlap"]
        ]

    raise ValueError(group)


def descriptive_spearman(rows, ai_field):
    pairs = [
        (
            r["LesionVolume_mL"],
            r[ai_field],
        )
        for r in rows
        if np.isfinite(r["LesionVolume_mL"])
        and np.isfinite(r[ai_field])
    ]

    if len(pairs) < 2:
        return {
            "N": len(pairs),
            "Rho": np.nan,
            "Subjects": [],
        }

    x = np.asarray(
        [p[0] for p in pairs],
        dtype=float,
    )
    y = np.asarray(
        [p[1] for p in pairs],
        dtype=float,
    )

    rho = spearmanr(
        x,
        y,
        nan_policy="omit",
    ).statistic

    subjects = [
        r["Subject"]
        for r in rows
        if np.isfinite(r["LesionVolume_mL"])
        and np.isfinite(r[ai_field])
    ]

    return {
        "N": len(pairs),
        "Rho": float(rho),
        "Subjects": subjects,
    }


def write_patient_output(rows):
    fields = [
        "Subject",
        "StrokeSide",
        "LesionVolume_mL",
        "Thalamus_IpsiOverlapPercent",
        "Hippocampus_IpsiOverlapPercent",
        "ThalamusDirect_GE1pct",
        "DeepROI_AnyOverlap",
        "PET_FDG_AI",
        "ASL_CBF_AI",
        "CTP_CBF_AI",
    ]

    with PATIENT_OUT.open(
        "w",
        newline="",
        encoding="utf-8",
    ) as f:
        writer = csv.DictWriter(
            f,
            fieldnames=fields,
        )
        writer.writeheader()

        for row in rows:
            writer.writerow(
                {
                    "Subject": row["Subject"],
                    "StrokeSide": row["StrokeSide"],
                    "LesionVolume_mL": fmt(
                        row["LesionVolume_mL"]
                    ),
                    "Thalamus_IpsiOverlapPercent": fmt(
                        row["Thalamus_IpsiOverlapPercent"]
                    ),
                    "Hippocampus_IpsiOverlapPercent": fmt(
                        row["Hippocampus_IpsiOverlapPercent"]
                    ),
                    "ThalamusDirect_GE1pct": row[
                        "ThalamusDirect_GE1pct"
                    ],
                    "DeepROI_AnyOverlap": row[
                        "DeepROI_AnyOverlap"
                    ],
                    "PET_FDG_AI": fmt(
                        row["PET_FDG_AI"]
                    ),
                    "ASL_CBF_AI": fmt(
                        row["ASL_CBF_AI"]
                    ),
                    "CTP_CBF_AI": fmt(
                        row["CTP_CBF_AI"]
                    ),
                }
            )


def build_spearman_table(rows):
    groups = [
        "ALL",
        "THALAMUS_SPARED_LT1PCT",
        "STRICT_DEEP_ROI_SPARED",
    ]

    result = []

    for group in groups:
        subset = group_rows(
            rows,
            group,
        )

        for modality, ai_field in MODALITIES.items():
            stat = descriptive_spearman(
                subset,
                ai_field,
            )

            rho = stat["Rho"]

            if np.isfinite(rho):
                if rho < 0:
                    interpretation = (
                        "Larger lesion volume tends to accompany "
                        "more negative thalamic AI"
                    )
                elif rho > 0:
                    interpretation = (
                        "Larger lesion volume tends to accompany "
                        "more positive thalamic AI"
                    )
                else:
                    interpretation = (
                        "No monotonic direction observed"
                    )
            else:
                interpretation = (
                    "Insufficient data"
                )

            result.append(
                {
                    "Group": group,
                    "Modality": modality,
                    "N": stat["N"],
                    "SpearmanRho_Volume_vs_AI": rho,
                    "Subjects": ";".join(
                        stat["Subjects"]
                    ),
                    "Interpretation": interpretation,
                }
            )

    return result


def write_spearman_output(rows):
    fields = [
        "Group",
        "Modality",
        "N",
        "SpearmanRho_Volume_vs_AI",
        "Subjects",
        "Interpretation",
    ]

    with SPEARMAN_OUT.open(
        "w",
        newline="",
        encoding="utf-8",
    ) as f:
        writer = csv.DictWriter(
            f,
            fieldnames=fields,
        )
        writer.writeheader()

        for row in rows:
            clean = dict(row)
            clean["SpearmanRho_Volume_vs_AI"] = fmt(
                row["SpearmanRho_Volume_vs_AI"]
            )
            writer.writerow(clean)


def plot_modality(rows, modality, ai_field):
    valid = [
        r
        for r in rows
        if np.isfinite(r["LesionVolume_mL"])
        and np.isfinite(r[ai_field])
    ]

    fig, ax = plt.subplots(
        figsize=(8.5, 6.5),
    )

    x = np.asarray(
        [r["LesionVolume_mL"] for r in valid],
        dtype=float,
    )
    y = np.asarray(
        [r[ai_field] for r in valid],
        dtype=float,
    )

    ax.scatter(
        x,
        y,
        s=80,
    )

    for r in valid:
        label = r["Subject"].replace(
            "sub-",
            "",
        )

        if r["ThalamusDirect_GE1pct"]:
            label += "†"

        ax.annotate(
            label,
            (
                r["LesionVolume_mL"],
                r[ai_field],
            ),
            xytext=(5, 5),
            textcoords="offset points",
        )

    ax.axhline(
        0,
        linewidth=1,
    )

    all_stat = descriptive_spearman(
        valid,
        ai_field,
    )

    spared = [
        r
        for r in valid
        if not r["ThalamusDirect_GE1pct"]
    ]

    spared_stat = descriptive_spearman(
        spared,
        ai_field,
    )

    title = (
        f"{modality}: lesion volume vs acute thalamic AI\n"
        f"All: rho={fmt(all_stat['Rho'], 2)}, N={all_stat['N']} | "
        f"Thalamus spared <1%: rho={fmt(spared_stat['Rho'], 2)}, "
        f"N={spared_stat['N']}"
    )

    ax.set_title(title)
    ax.set_xlabel(
        "Acute ischemic lesion volume (mL)"
    )
    ax.set_ylabel(
        "Thalamic median AI (ipsi - contra) / (ipsi + contra)"
    )

    ax.grid(
        alpha=0.25,
    )

    fig.tight_layout()

    safe_modality = modality.replace(
        "/",
        "-",
    )

    out = (
        OUT_DIR
        / f"PSE_ACUTE_THALAMUS_VOLUME_vs_{safe_modality}_AI_v01.png"
    )

    fig.savefig(
        out,
        dpi=200,
        bbox_inches="tight",
    )

    plt.close(fig)

    return out


# ============================================================================
# Main

def main():
    OUT_DIR.mkdir(
        parents=True,
        exist_ok=True,
    )

    print("=" * 76)
    print("PSE ACUTE THALAMUS: LESION VOLUME ASSOCIATION")
    print("=" * 76)
    print(f"Input : {INPUT_FILE}")
    print(f"Output: {OUT_DIR}")
    print("=" * 76)

    if not INPUT_FILE.is_file():
        raise FileNotFoundError(
            f"Input patient-level file not found: {INPUT_FILE}"
        )

    rows = read_patient_table()

    write_patient_output(
        rows
    )

    stats = build_spearman_table(
        rows
    )

    write_spearman_output(
        stats
    )

    figures = []

    for modality, ai_field in MODALITIES.items():
        figures.append(
            plot_modality(
                rows,
                modality,
                ai_field,
            )
        )

    print()
    print("Patient-level table:")
    print(f"  {PATIENT_OUT}")

    print("Spearman summary:")
    print(f"  {SPEARMAN_OUT}")

    print("Figures:")

    for fig in figures:
        print(f"  {fig}")

    print()
    print("Descriptive Spearman rho:")

    for row in stats:
        print(
            f"  {row['Group']} | "
            f"{row['Modality']} | "
            f"N={row['N']} | "
            f"rho={fmt(row['SpearmanRho_Volume_vs_AI'], 3)}"
        )

    print()
    print(
        "Reminder: rho is descriptive only. "
        "No p-values or inferential conclusions should be drawn "
        "from this pilot."
    )

    print("=" * 76)


if __name__ == "__main__":
    main()
